"""empty message

Revision ID: 0036831f9eb7
Revises: 121dfc87fcca
Create Date: 2022-05-20 11:36:51.098772

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0036831f9eb7"
down_revision = "121dfc87fcca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_param",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=True),
        sa.Column("value", sa.String(length=8000), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_param_id"), "task_param", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_param_task_id"), "task_param", ["task_id"], unique=False
    )
    op.drop_index("ix_task_params_id", table_name="task_params")
    op.drop_index("ix_task_params_task_id", table_name="task_params")
    op.drop_table("task_params")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_params",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("key", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("value", sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="task_params_task_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="task_params_pkey"),
    )
    op.create_index("ix_task_params_task_id", "task_params", ["task_id"], unique=False)
    op.create_index("ix_task_params_id", "task_params", ["id"], unique=False)
    op.drop_index(op.f("ix_task_param_task_id"), table_name="task_param")
    op.drop_index(op.f("ix_task_param_id"), table_name="task_param")
    op.drop_table("task_param")
    # ### end Alembic commands ###
