"""empty message

Revision ID: 062d92ced96d
Revises: f178cbbeaa5f
Create Date: 2021-03-03 13:21:05.536766

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "062d92ced96d"
down_revision = "f178cbbeaa5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connection_gpg", "passphrase")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connection_gpg",
        sa.Column("passphrase", sa.TEXT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
