"""empty message

Revision ID: 0983322548b6
Revises: 21d3374cb7af
Create Date: 2022-04-14 11:40:29.696430

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0983322548b6"
down_revision = "21d3374cb7af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connection_database", sa.Column("timeout", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connection_database", "timeout")
    # ### end Alembic commands ###
