"""empty message

Revision ID: 0ebf4c788f71
Revises: 7e948796b90f
Create Date: 2021-11-04 09:56:24.790906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0ebf4c788f71'
down_revision = '7e948796b90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('source_require_sql_output', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'source_require_sql_output')
    # ### end Alembic commands ###
