"""empty message

Revision ID: 121dfc87fcca
Revises: 0983322548b6
Create Date: 2022-05-20 10:33:32.203084

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "121dfc87fcca"
down_revision = "0983322548b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_params",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=True),
        sa.Column("value", sa.String(length=8000), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_params_id"), "project_params", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_project_params_project_id"),
        "project_params",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "task_params",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=True),
        sa.Column("value", sa.String(length=8000), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_params_id"), "task_params", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_params_task_id"), "task_params", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_params_task_id"), table_name="task_params")
    op.drop_index(op.f("ix_task_params_id"), table_name="task_params")
    op.drop_table("task_params")
    op.drop_index(op.f("ix_project_params_project_id"), table_name="project_params")
    op.drop_index(op.f("ix_project_params_id"), table_name="project_params")
    op.drop_table("project_params")
    # ### end Alembic commands ###
