"""empty message

Revision ID: 7a2ba259228d
Revises: 062d92ced96d
Create Date: 2021-03-15 09:03:43.265647

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a2ba259228d"
down_revision = "062d92ced96d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_file", sa.Column("file_hash", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_file", "file_hash")
    # ### end Alembic commands ###
