"""empty message

Revision ID: 7e948796b90f
Revises: bd39e892dfc0
Create Date: 2021-11-01 16:06:06.240088

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e948796b90f"
down_revision = "bd39e892dfc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("source_cache", sa.Text(), nullable=True))
    op.add_column("task", sa.Column("enable_source_cache", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_task_enable_source_cache"),
        "task",
        ["enable_source_cache"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_enable_source_cache"), table_name="task")
    op.drop_column("task", "enable_source_cache")
    op.drop_column("task", "source_cache")
    # ### end Alembic commands ###
