"""empty message

Revision ID: 88d238f430da
Revises: 9221c436d9ad
Create Date: 2021-04-19 15:00:31.424975

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88d238f430da"
down_revision = "9221c436d9ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("account_name", sa.String(length=200), nullable=True)
    )
    op.add_column("user", sa.Column("email", sa.String(length=200), nullable=True))
    op.alter_column(
        "user", "full_name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.drop_index("ix_user_user_id", table_name="user")
    op.create_index(
        op.f("ix_user_account_name"), "user", ["account_name"], unique=False
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.drop_column("user", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "user_id", sa.VARCHAR(length=120), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_account_name"), table_name="user")
    op.create_index("ix_user_user_id", "user", ["user_id"], unique=False)
    op.alter_column(
        "user", "full_name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.drop_column("user", "email")
    op.drop_column("user", "account_name")
    # ### end Alembic commands ###
