"""empty message

Revision ID: 8ac86850e7af
Revises: d0a9d462fbde
Create Date: 2021-02-01 08:54:59.799525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ac86850e7af"
down_revision = "d0a9d462fbde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("max_retries", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_max_retries"), "task", ["max_retries"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_max_retries"), table_name="task")
    op.drop_column("task", "max_retries")
    # ### end Alembic commands ###
