"""empty message

Revision ID: 9221c436d9ad
Revises: dff80fd96b34
Create Date: 2021-03-24 14:43:26.934701

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9221c436d9ad"
down_revision = "dff80fd96b34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "destination_file_line_terminator", sa.String(length=10), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "destination_file_line_terminator")
    # ### end Alembic commands ###
