"""empty message

Revision ID: bd39e892dfc0
Revises: e1e2877db354
Create Date: 2021-09-23 15:52:23.552320

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd39e892dfc0"
down_revision = "e1e2877db354"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connection", "name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "connection_database", "type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "connection_database",
        "connection_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "connection_database",
        "name",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_database",
        "connection_string",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "connection_database_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "connection_ftp", "connection_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "connection_ftp", "name", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_ftp", "address", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_ftp", "path", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_ftp",
        "username",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_ftp", "password", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "connection_gpg", "connection_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "connection_gpg", "name", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_sftp", "connection_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "connection_sftp", "name", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_sftp",
        "address",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_sftp", "path", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_sftp", "password", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "connection_smb", "connection_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "connection_smb", "name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "connection_smb",
        "share_name",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_smb", "path", existing_type=sa.VARCHAR(length=1000), nullable=True
    )
    op.alter_column(
        "connection_smb",
        "username",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_smb", "password", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "connection_smb",
        "server_ip",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_smb",
        "server_name",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "connection_ssh", "connection_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "connection_ssh", "name", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_ssh", "address", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "connection_ssh",
        "username",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "connection_ssh", "password", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "login", "username", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "login_type", "name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "quote_level", "name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "task_destination_file_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "task_processing_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "task_source_query_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "task_source_type", "name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_source_type", "name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "task_source_query_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "task_processing_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "task_destination_file_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "quote_level", "name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "login_type", "name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "login", "username", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "connection_ssh", "password", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "connection_ssh",
        "username",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "connection_ssh",
        "address",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_ssh", "name", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "connection_ssh", "connection_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "connection_smb",
        "server_name",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_smb",
        "server_ip",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_smb", "password", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "connection_smb",
        "username",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_smb", "path", existing_type=sa.VARCHAR(length=1000), nullable=False
    )
    op.alter_column(
        "connection_smb",
        "share_name",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_smb", "name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "connection_smb", "connection_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "connection_sftp", "password", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "connection_sftp", "path", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "connection_sftp",
        "address",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_sftp", "name", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "connection_sftp", "connection_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "connection_gpg", "name", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "connection_gpg", "connection_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "connection_ftp", "password", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "connection_ftp",
        "username",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_ftp", "path", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "connection_ftp",
        "address",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_ftp", "name", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "connection_ftp", "connection_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "connection_database_type",
        "name",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "connection_database",
        "connection_string",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "connection_database",
        "name",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "connection_database",
        "connection_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "connection_database", "type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "connection", "name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    # ### end Alembic commands ###
