"""empty message

Revision ID: c7e5824099a9
Revises: 8ac86850e7af
Create Date: 2021-02-23 12:23:25.485247

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7e5824099a9"
down_revision = "8ac86850e7af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection_gpg",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("key", sa.String(length=8000), nullable=True),
        sa.Column("passphrase", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connection_gpg_connection_id"),
        "connection_gpg",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connection_gpg_id"), "connection_gpg", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connection_gpg_id"), table_name="connection_gpg")
    op.drop_index(op.f("ix_connection_gpg_connection_id"), table_name="connection_gpg")
    op.drop_table("connection_gpg")
    # ### end Alembic commands ###
