"""empty message

Revision ID: d0a9d462fbde
Revises: a431d98b274c
Create Date: 2021-01-26 09:51:44.424817

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d0a9d462fbde"
down_revision = "a431d98b274c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("email_completion_file_embed", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "email_completion_file_embed")
    # ### end Alembic commands ###
