"""empty message

Revision ID: dff80fd96b34
Revises: 7a2ba259228d
Create Date: 2021-03-16 08:42:47.704031

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dff80fd96b34"
down_revision = "7a2ba259228d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("est_duration", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_task_est_duration"), "task", ["est_duration"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_est_duration"), table_name="task")
    op.drop_column("task", "est_duration")
    # ### end Alembic commands ###
