"""empty message

Revision ID: e1e2877db354
Revises: 78a9731d2953
Create Date: 2021-08-18 12:50:08.477133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1e2877db354"
down_revision = "78a9731d2953"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("sequence_tasks", sa.Integer(), nullable=True))
    op.add_column("task", sa.Column("order", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_order"), "task", ["order"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_order"), table_name="task")
    op.drop_column("task", "order")
    op.drop_column("project", "sequence_tasks")
    # ### end Alembic commands ###
