"""empty message

Revision ID: f178cbbeaa5f
Revises: 405d512e10c7
Create Date: 2021-03-03 11:19:07.375154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f178cbbeaa5f"
down_revision = "405d512e10c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("file_gpg", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_file_gpg"), "task", ["file_gpg"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_file_gpg"), table_name="task")
    op.drop_column("task", "file_gpg")
    # ### end Alembic commands ###
