"""empty message

Revision ID: 040c7dc467f2
Revises: 882dc38883bf
Create Date: 2020-10-02 13:42:03.505484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "040c7dc467f2"
down_revision = "882dc38883bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("query_params", sa.String(length=8000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "query_params")
    # ### end Alembic commands ###
