"""empty message

Revision ID: 1252a267da96
Revises: 2f10875c530f
Create Date: 2020-10-08 17:57:28.006870

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1252a267da96"
down_revision = "2f10875c530f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("email_completion_dont_send_empty_file", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "email_completion_dont_send_empty_file")
    # ### end Alembic commands ###
