"""empty message

Revision ID: 2f10875c530f
Revises: 076b117850e4
Create Date: 2020-10-08 13:31:27.915064

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f10875c530f"
down_revision = "076b117850e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("creating table")
    op.create_table(
        "quote_level",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    print("creating index")
    op.create_index(op.f("ix_quote_level_id"), "quote_level", ["id"], unique=False)
    print("adding column")
    op.add_column(
        "task", sa.Column("destination_quote_level_id", sa.Integer(), nullable=True)
    )
    print("adding key")
    op.create_foreign_key(
        None, "task", "quote_level", ["destination_quote_level_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "destination_quote_level_id")
    op.drop_index(op.f("ix_quote_level_id"), table_name="quote_level")
    op.drop_table("quote_level")
    # ### end Alembic commands ###
