"""empty message

Revision ID: 32a82d228440
Revises: d8adc919144b
Create Date: 2021-01-26 09:52:47.404561

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32a82d228440"
down_revision = "d8adc919144b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_connection_database_type_id"),
        "connection_database",
        ["type_id"],
        unique=False,
    )
    op.add_column(
        "task", sa.Column("email_completion_file_embed", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_task_destination_file_type_id"),
        "task",
        ["destination_file_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_processing_type_id"), "task", ["processing_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_source_query_type_id"),
        "task",
        ["source_query_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_source_type_id"), "task", ["source_type_id"], unique=False
    )
    op.create_index(op.f("ix_task_status_id"), "task", ["status_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_status_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_query_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_processing_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_destination_file_type_id"), table_name="task")
    op.drop_column("task", "email_completion_file_embed")
    op.drop_index(
        op.f("ix_connection_database_type_id"), table_name="connection_database"
    )
    # ### end Alembic commands ###
