"""empty message

Revision ID: 3daa9bdf0b76
Revises: 4dead239fd24
Create Date: 2020-12-04 07:54:20.334458

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3daa9bdf0b76"
down_revision = "4dead239fd24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_task_log_status_date_error",
        "task_log",
        ["status_date", "error"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_log_status_date_error", table_name="task_log")
    # ### end Alembic commands ###
