"""empty message

Revision ID: 40659865cc2d
Revises: 3d8418608931
Create Date: 2021-11-04 09:58:57.054592

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '40659865cc2d'
down_revision = '3d8418608931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('source_require_sql_output', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'source_require_sql_output')
    # ### end Alembic commands ###
