"""empty message

Revision ID: 45a2e611057b
Revises: 9e6d9818381c
Create Date: 2022-05-23 11:38:28.293072

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45a2e611057b"
down_revision = "9e6d9818381c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_param", sa.Column("sensitive", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_project_param_sensitive"), "project_param", ["sensitive"], unique=False
    )
    op.add_column("task_param", sa.Column("sensitive", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_task_param_sensitive"), "task_param", ["sensitive"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_param_sensitive"), table_name="task_param")
    op.drop_column("task_param", "sensitive")
    op.drop_index(op.f("ix_project_param_sensitive"), table_name="project_param")
    op.drop_column("project_param", "sensitive")
    # ### end Alembic commands ###
