"""empty message

Revision ID: 4dead239fd24
Revises: a0968f5376d6
Create Date: 2020-12-04 07:43:57.721659

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4dead239fd24"
down_revision = "a0968f5376d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(
    #     op.f("ix_connection_database_connection_id"),
    #     "connection_database",
    #     ["connection_id"],
    #     unique=False,
    # )
    op.create_index(
        op.f("ix_connection_ftp_connection_id"),
        "connection_ftp",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connection_sftp_connection_id"),
        "connection_sftp",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connection_smb_connection_id"),
        "connection_smb",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connection_ssh_connection_id"),
        "connection_ssh",
        ["connection_id"],
        unique=False,
    )
    op.create_index(op.f("ix_task_created"), "task", ["created"], unique=False)
    op.create_index(op.f("ix_task_creator_id"), "task", ["creator_id"], unique=False)
    op.create_index(
        op.f("ix_task_destination_ftp"), "task", ["destination_ftp"], unique=False
    )
    op.create_index(
        op.f("ix_task_destination_ftp_id"), "task", ["destination_ftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_destination_quote_level_id"),
        "task",
        ["destination_quote_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_destination_sftp"), "task", ["destination_sftp"], unique=False
    )
    op.create_index(
        op.f("ix_task_destination_sftp_id"),
        "task",
        ["destination_sftp_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_destination_smb"), "task", ["destination_smb"], unique=False
    )
    op.create_index(
        op.f("ix_task_destination_smb_id"), "task", ["destination_smb_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_email_completion"), "task", ["email_completion"], unique=False
    )
    op.create_index(op.f("ix_task_email_error"), "task", ["email_error"], unique=False)
    op.create_index(op.f("ix_task_enabled"), "task", ["enabled"], unique=False)
    op.create_index(
        op.f("ix_task_last_run_job_id"), "task", ["last_run_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_processing_ftp_id"), "task", ["processing_ftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_processing_sftp_id"), "task", ["processing_sftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_processing_smb_id"), "task", ["processing_smb_id"], unique=False
    )
    op.create_index(op.f("ix_task_project_id"), "task", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_task_query_ftp_id"), "task", ["query_ftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_query_sftp_id"), "task", ["query_sftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_query_smb_id"), "task", ["query_smb_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_source_database_id"), "task", ["source_database_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_source_ftp_id"), "task", ["source_ftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_source_sftp_id"), "task", ["source_sftp_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_source_smb_id"), "task", ["source_smb_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_source_ssh_id"), "task", ["source_ssh_id"], unique=False
    )
    op.create_index(op.f("ix_task_updated"), "task", ["updated"], unique=False)
    op.create_index(op.f("ix_task_updater_id"), "task", ["updater_id"], unique=False)
    op.create_index(op.f("ix_task_log_job_id"), "task_log", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_task_log_status_id"), "task_log", ["status_id"], unique=False
    )
    op.create_index(op.f("ix_task_log_task_id"), "task_log", ["task_id"], unique=False)
    op.create_index(op.f("ix_user_user_id"), "user", ["user_id"], unique=False)
    # op.create_index(
    #     op.f("ix_connection_database_type_id"),
    #     "connection_database",
    #     ["type_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_task_destination_file_type_id"),
    #     "task",
    #     ["destination_file_type_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_task_processing_type_id"), "task", ["processing_type_id"], unique=False
    # )
    # op.create_index(
    #     op.f("ix_task_source_query_type_id"),
    #     "task",
    #     ["source_query_type_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_task_source_type_id"), "task", ["source_type_id"], unique=False
    # )
    # op.create_index(op.f("ix_task_status_id"), "task", ["status_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_index(op.f("ix_task_log_task_id"), table_name="task_log")
    op.drop_index(op.f("ix_task_log_status_id"), table_name="task_log")
    op.drop_index(op.f("ix_task_log_job_id"), table_name="task_log")
    op.drop_index(op.f("ix_task_updater_id"), table_name="task")
    op.drop_index(op.f("ix_task_updated"), table_name="task")
    op.drop_index(op.f("ix_task_status_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_ssh_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_smb_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_sftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_query_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_ftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_source_database_id"), table_name="task")
    op.drop_index(op.f("ix_task_query_smb_id"), table_name="task")
    op.drop_index(op.f("ix_task_query_sftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_query_ftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_project_id"), table_name="task")
    op.drop_index(op.f("ix_task_processing_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_processing_smb_id"), table_name="task")
    op.drop_index(op.f("ix_task_processing_sftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_processing_ftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_last_run_job_id"), table_name="task")
    op.drop_index(op.f("ix_task_enabled"), table_name="task")
    op.drop_index(op.f("ix_task_email_error"), table_name="task")
    op.drop_index(op.f("ix_task_email_completion"), table_name="task")
    op.drop_index(op.f("ix_task_destination_smb_id"), table_name="task")
    op.drop_index(op.f("ix_task_destination_smb"), table_name="task")
    op.drop_index(op.f("ix_task_destination_sftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_destination_sftp"), table_name="task")
    op.drop_index(op.f("ix_task_destination_quote_level_id"), table_name="task")
    op.drop_index(op.f("ix_task_destination_ftp_id"), table_name="task")
    op.drop_index(op.f("ix_task_destination_ftp"), table_name="task")
    op.drop_index(op.f("ix_task_destination_file_type_id"), table_name="task")
    op.drop_index(op.f("ix_task_creator_id"), table_name="task")
    op.drop_index(op.f("ix_task_created"), table_name="task")
    op.drop_index(op.f("ix_connection_ssh_connection_id"), table_name="connection_ssh")
    op.drop_index(op.f("ix_connection_smb_connection_id"), table_name="connection_smb")
    op.drop_index(
        op.f("ix_connection_sftp_connection_id"), table_name="connection_sftp"
    )
    op.drop_index(op.f("ix_connection_ftp_connection_id"), table_name="connection_ftp")
    op.drop_index(
        op.f("ix_connection_database_type_id"), table_name="connection_database"
    )
    op.drop_index(
        op.f("ix_connection_database_connection_id"), table_name="connection_database"
    )
    # ### end Alembic commands ###
