"""empty message

Revision ID: 677073547b37
Revises: ebcca0fb8b4c
Create Date: 2022-04-14 11:41:56.818010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "677073547b37"
down_revision = "ebcca0fb8b4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connection_database", sa.Column("timeout", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connection_database", "timeout")
    # ### end Alembic commands ###
