"""empty message

Revision ID: 6abd3322006e
Revises: b26e97573532
Create Date: 2021-08-18 12:52:40.891180

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6abd3322006e"
down_revision = "b26e97573532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("sequence_tasks", sa.Integer(), nullable=True))
    op.add_column("task", sa.Column("order", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_order"), "task", ["order"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_order"), table_name="task")
    op.drop_column("task", "order")
    op.drop_column("project", "sequence_tasks")
    # ### end Alembic commands ###
