"""empty message

Revision ID: 6b8978d637c5
Revises: 0fe33867bdbf
Create Date: 2023-08-03 12:53:03.650434

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6b8978d637c5'
down_revision = '0fe33867bdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_sftp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_password', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # move passwords on connections that have a key into the key_password field and clear the
    # password field.
    op.execute('update connection_sftp set key_password=password where key is not null')
    op.execute('update connection_sftp set password=null where key is not null and key_password=password')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_sftp', schema=None) as batch_op:
        batch_op.drop_column('key_password')

    # ### end Alembic commands ###
