"""empty message

Revision ID: 73214b16a952
Revises: 9ba33783b877
Create Date: 2024-08-09 17:56:31.257536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73214b16a952'
down_revision = '9ba33783b877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_database', schema=None) as batch_op:
        batch_op.drop_index('ix_connection_database_type_id')

    with op.batch_alter_table('connection_database_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_database_type_id'), ['id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_destination_file_type_id')
        batch_op.drop_index('ix_task_processing_type_id')
        batch_op.drop_index('ix_task_status_id')

    with op.batch_alter_table('task_destination_file_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_destination_file_type_id'), ['id'], unique=False)

    with op.batch_alter_table('task_processing_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_processing_type_id'), ['id'], unique=False)

    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_status_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status_id'))

    with op.batch_alter_table('task_processing_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_processing_type_id'))

    with op.batch_alter_table('task_destination_file_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_destination_file_type_id'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('ix_task_status_id', ['status_id'], unique=False)
        batch_op.create_index('ix_task_processing_type_id', ['processing_type_id'], unique=False)
        batch_op.create_index('ix_task_destination_file_type_id', ['destination_file_type_id'], unique=False)

    with op.batch_alter_table('connection_database_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_database_type_id'))

    with op.batch_alter_table('connection_database', schema=None) as batch_op:
        batch_op.create_index('ix_connection_database_type_id', ['type_id'], unique=False)

    # ### end Alembic commands ###
