"""empty message

Revision ID: 8a7fc838f6ed
Revises: 45a2e611057b
Create Date: 2022-06-15 14:57:27.741619

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8a7fc838f6ed"
down_revision = "45a2e611057b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "task",
        "source_code",
        existing_type=sa.VARCHAR(length=8000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "source_code",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=8000),
        existing_nullable=True,
    )
    op.alter_column(
        "task",
        "updated",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
