"""empty message

Revision ID: 952225e66486
Revises: 32a82d228440
Create Date: 2021-02-01 09:00:37.292283

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "952225e66486"
down_revision = "32a82d228440"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("max_retries", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_max_retries"), "task", ["max_retries"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_max_retries"), table_name="task")
    op.drop_column("task", "max_retries")
    # ### end Alembic commands ###
