"""empty message

Revision ID: 9e6d9818381c
Revises: 677073547b37
Create Date: 2022-05-20 12:55:24.216264

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e6d9818381c"
down_revision = "677073547b37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_param",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=True),
        sa.Column("value", sa.String(length=8000), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_param_id"), "project_param", ["id"], unique=False)
    op.create_index(
        op.f("ix_project_param_project_id"),
        "project_param",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "task_param",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=True),
        sa.Column("value", sa.String(length=8000), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_param_id"), "task_param", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_param_task_id"), "task_param", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_param_task_id"), table_name="task_param")
    op.drop_index(op.f("ix_task_param_id"), table_name="task_param")
    op.drop_table("task_param")
    op.drop_index(op.f("ix_project_param_project_id"), table_name="project_param")
    op.drop_index(op.f("ix_project_param_id"), table_name="project_param")
    op.drop_table("project_param")
    # ### end Alembic commands ###
