"""empty message

Revision ID: a0968f5376d6
Revises: be8459acb657
Create Date: 2020-12-04 07:36:11.481926

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0968f5376d6"
down_revision = "be8459acb657"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_task_log_error"), "task_log", ["error"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_log_error"), table_name="task_log")
    # ### end Alembic commands ###
