"""empty message

Revision ID: a61947d2caf8
Revises: 73214b16a952
Create Date: 2025-08-08 09:11:16.465770

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a61947d2caf8'
down_revision = '73214b16a952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_smb', schema=None) as batch_op:
        batch_op.drop_column('server_ip')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_smb_ignore_subfolders', sa.Integer(), nullable=True))
        batch_op.drop_column('source_smb_ignore_delimiter')
        batch_op.drop_column('source_smb_delimiter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_smb_delimiter', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source_smb_ignore_delimiter', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('source_smb_ignore_subfolders')

    with op.batch_alter_table('connection_smb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_ip', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
