"""empty message

Revision ID: b26e97573532
Revises: abf5bb5015a3
Create Date: 2021-04-19 15:33:24.282884

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b26e97573532"
down_revision = "abf5bb5015a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
