"""empty message

Revision ID: be8459acb657
Revises: dadd9ecfd812
Create Date: 2020-12-04 07:33:32.889107

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be8459acb657"
down_revision = "dadd9ecfd812"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_task_log_status_date"), "task_log", ["status_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_log_status_date"), table_name="task_log")
    # ### end Alembic commands ###
