"""empty message

Revision ID: c823e1777083
Revises: 6d8c011551a3
Create Date: 2021-03-15 09:04:50.356196

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c823e1777083"
down_revision = "6d8c011551a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_file", sa.Column("file_hash", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_file", "file_hash")
    # ### end Alembic commands ###
