"""empty message

Revision ID: c951ce57629c
Revises: c823e1777083
Create Date: 2021-03-16 08:46:41.158837

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c951ce57629c"
down_revision = "c823e1777083"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("est_duration", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_task_est_duration"), "task", ["est_duration"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_est_duration"), table_name="task")
    op.drop_column("task", "est_duration")
    # ### end Alembic commands ###
