"""empty message

Revision ID: d3ea7dc4570a
Revises: 42792b30dd24
Create Date: 2021-02-24 08:58:18.765375

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3ea7dc4570a"
down_revision = "42792b30dd24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("file_gpg_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_task_file_gpg_id"), "task", ["file_gpg_id"], unique=False)
    op.create_foreign_key(None, "task", "connection_gpg", ["file_gpg_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_index(op.f("ix_task_file_gpg_id"), table_name="task")
    op.drop_column("task", "file_gpg_id")
    # ### end Alembic commands ###
