"""empty message

Revision ID: dadd9ecfd812
Revises: fdb359e4265b
Create Date: 2020-10-09 13:21:09.445814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dadd9ecfd812"
down_revision = "fdb359e4265b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "source_ssh_command")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "source_ssh_command",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
