"""empty message

Revision ID: ebcca0fb8b4c
Revises: 40659865cc2d
Create Date: 2022-01-19 09:17:15.186037

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ebcca0fb8b4c"
down_revision = "40659865cc2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("destination_sftp_dont_send_empty_file", sa.Integer(), nullable=True),
    )
    op.add_column(
        "task",
        sa.Column("destination_ftp_dont_send_empty_file", sa.Integer(), nullable=True),
    )
    op.add_column(
        "task",
        sa.Column("destination_smb_dont_send_empty_file", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "destination_smb_dont_send_empty_file")
    op.drop_column("task", "destination_ftp_dont_send_empty_file")
    op.drop_column("task", "destination_sftp_dont_send_empty_file")
    # ### end Alembic commands ###
