"""empty message

Revision ID: fdb359e4265b
Revises: a73e35294956
Create Date: 2020-10-09 11:49:53.314081

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fdb359e4265b"
down_revision = "a73e35294956"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("source_ssh_command", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "source_ssh_command")
    # ### end Alembic commands ###
