name: 🔍 lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v6

    - name: ⎔ Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 18

    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@v6

    - name: 📥 Download deps
      run: pnpm install --frozen-lockfile

    - name: 🐍 Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: 🪐 Setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e

    - name: 📥 Install
      run: |
        sudo apt update
        sudo apt install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config build-essential libssl-dev libffi-dev curl git wget libldap2-dev python3-dev python3-pip python3-setuptools unixodbc unixodbc-dev libpq-dev nginx sqlite3 libsqlite3-0 libsasl2-dev libxml2-dev libxmlsec1-dev libxmlsec1-dev redis-server ufw gnupg
        uv sync --frozen --group dev

    - name: 🔍 Lint
      run: pnpm test
