name: 🔍 lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v6

    - name: ⎔ Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: 📥 Download deps
      uses: bahmutov/npm-install@v1
      with:
        useLockFile: false

    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 🎶 Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.2.1

    - name: 📥 Install
      run: |
        sudo apt update
        sudo apt install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config build-essential libssl-dev libffi-dev curl git wget libldap2-dev python3-dev python3-pip python3-setuptools unixodbc unixodbc-dev libpq-dev nginx sqlite3 libsqlite3-0 libsasl2-dev libxml2-dev libxmlsec1-dev libxmlsec1-dev redis-server ufw gnupg
        poetry install

    - name: 🔍 Lint
      run: npm run test
