name: 🚀 Release

on:
  push:
    branches: [main, alpha]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      last_release_version: ${{ steps.semantic.outputs.last_release_version }}

    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: 🧹 Cleanup apt list
      uses: christopherpickering/no-azure-action@v1.1.0

    - name: ⎔ Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@v6

    - name: 📥 Download deps
      run: pnpm install --frozen-lockfile

    - name: 🐍 Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: 🔧 Setup uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: 📥 Install OS deps
      run: |
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config build-essential libssl-dev libffi-dev curl git wget libldap2-dev python3-dev python3-pip python3-setuptools unixodbc unixodbc-dev libpq-dev nginx sqlite3 libsqlite3-0 libsasl2-dev libxml2-dev libxmlsec1-dev libxmlsec1-dev redis-server ufw gnupg
      env:
        PYTHONWARNINGS: ignore

    - name: 🚀 Semantic Release
      uses: cycjimmy/semantic-release-action@v6.0.0
      id: semantic
      with:
        semantic_version: 18
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
