name: 🚀 Release

on:
  push:
    branches: [main, alpha]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      last_release_version: ${{ steps.semantic.outputs.last_release_version }}

    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: 🧹 Cleanup apt list
      uses: christopherpickering/no-azure-action@v1.1.0

    - name: ⎔ Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@v4

    - name: 📥 Download deps
      run: pnpm install --frozen-lockfile

    - name: 🐍 Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: 🔧 Setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6

    - name: 🚀 Semantic Release
      uses: cycjimmy/semantic-release-action@v6.0.0
      id: semantic
      with:
        semantic_version: 18
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
